#!/bin/sh
uid=`id -u`
dir=/run/user/$uid/state
is_mounted=`mount | grep "$dir" | wc -l`

if [ "X$is_mounted" != "X0" ]; then
    fusermount -u -z "$dir"
fi

if [ ! -e "$dir" ]; then
    mkdir -p "$dir"
fi

hooks_dir=/var/lib/statefs/hooks
if [[ -d "$hooks_dir" ]]; then
    for hook in `find /var/lib/statefs/hooks/ -name 'prestart*'`; do
        if [[ -x "$hook" ]]; then
            echo "Prestart hook $hook"
            exec "$hook"
        else
            echo "$hook is not executable"
        fi
    done
fi
